### ISSUE TITLE
Add context menu support

### ISSUE THREAD

**Issue by shunia** [zenotsai/json2dts-gen#1]
Great plugin, but I'd rather have it:
1. Add `JSON2dts` to the context menu (right click) for better DX, it's way slower to search in commands and no need to remember another short cut;
2. Supports in-place replacement for given JSON content, so you don't need to open another window to copy-paste json content and then copy the generated typescript definitions back into your code;

**Comment by zenotsai** [comment]
@shunia 
good idea, this is also in my plan and is already supported in version 0.0.7
